### ISSUE TITLE
[Localisation]Spiritualist Pilgrimage localisation problem

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#131]
From the Paradox forum : 1.4 beta 1: the 'A Conspiracy Unfolding' event in the pilgrimace event chain has a typo in the last sentence. "This is why he stayed quit about his reasons until now." -> quiet

**Comment by Deytron** [comment]
Oh, so that wasn't me. I saw that when I translated the file. But there's an even bigger typo in the same file. I won't do another pull request, but here is the sentence, line 74 : 

"They are unsuprisingly nowhere to be found now. as it seems someone helped them to escape which buoys up the governors story of an infiltration of our security staff"

I don't think that makes a lot of sense. Plus, a capital letter is needed and the word "buoys" doesn't exist in this world.

**Comment by tzerrell** [comment]
I revised the part @Deytron was concerned about in 741541e and the original typo had already been corrected, so I'm closing this.

@Deytron I'm assuming you wrote something reasonable for the French so I don't think there's any particular need to update it. But if you want to go ahead.
