### ISSUE TITLE
[Music Tour] Don't send to empire of same species - Testing Needed

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#148]
This event should not spawn when both empires have the same primary species (due to the text referring to alien music, translating lyrics, etc).

**Comment by Hoeya** [comment]
I'll take a look at this and see if I can fix the issue.

**Comment by Hoeya** [comment]
Testing Information - 

This is going to be somewhat involved, having an older game around would be wise. File should be in the dev repository. 

1.) Open the file, and comment out 

 mean_time_to_happen = {
        months = 970
    }   

2.) Find old game. Open old game. 

3.) Determine who around you has the fanatic induvidualists or induvidualist traits. Make a note of them. 

4.) Unpause game. If they are close enough to you, you should get an event for each one that's around you, once per day, until there are none left. (I'm not sure I like that part of the code, but not what I was fixing.)

5.) debugtooltip to find out the id's of your induvidualist neighbors. Probably be a good idea if it's fairly large. 

6.) Switch over to an induvidualist neighbor, and find a faction for independence and grant it. Hopefully they'll be factions that still have induvidualist traits, otherwise, you'll have to make one. 

7.) Unpause game and see if new nations pop up or not. 

**\- Things to look out for -** 

Blank names on the description, as in the nations or planets that don't exist. This should not occur. 

New nations with same species - should not generate events. 

New nations that are actually generating events - check and make sure they aren't subspecies. Subspecies should not fire. 

Other things I did not catch.

**Comment by Deytron** [comment]
Report of the test : 
- Event happened for every individualist nation close to mine
- Took control of one of these nations, event happened
- Granted independance to a faction, event happened after a long time with the vassalised nation

**Comment by Hoeya** [comment]
May have fixed issue. Needs re-testing. Same pattern as above, in **dev** repository.

**Comment by Deytron** [comment]
Confirm working now. Closing issue
