### ISSUE TITLE
Asteroid Derelict Structure failure event localisation has scope error

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#193]
This failure event reportedly does not return the correct text in a way that sounds like a scope error.

**Comment by tzerrell** [comment]
Testing indicated this was a false report; closing.

**Comment by tzerrell** [comment]
Re-opening -- apparently the issue was in the initial anomaly not the failure event

**Comment by nCrazed** [comment]
Is this the fact that leader's name is not being included in the text?

Could this be the same problem as discussed in #163 where it's impossible to refer to the leader name from category events?

Since the event texts were re-written by a writer after that conclusion and then included in the release I assumed that this was resolved.

**Comment by tzerrell** [comment]
@nCrazed fixed this with c068738
