### ISSUE TITLE
New Anomaly: "Abandoned Mecha"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#211]
This is a proposed anomaly.

This anomaly would only occur on Tomb worlds.

Upon discovery:
**Unusual Ruins**
_“The world of [Planet Name] is in a nuclear winter, which has lasted for around 1,000 years according to radiometric dating. Like all tomb worlds, it is covered in ruins of the civilization that once graced its surface. However, many of these, some of which are visible from orbit, cannot be compared to any previously discovered archaeological sites.”_

This would make an anomaly that would be fairly easy: level 1, difficulty 10, maybe?

Upon completion:
**Abandoned Mecha**
_“It would appear as though the defunct civilization on [Planet Name] had been in a state of worldwide war long before the invention of nuclear weapons. Before the breakthroughs were made that allowed such devices to even be theorized, they invested a considerable amount of effort into making bigger and better weapons of war. In particular, they developed armoured bipedal and quadrupedal machines, similar to tanks, which have quickly become referred to as “mecha”.

After several decades of waging war with these machines, nuclear power was discovered, and atomic weapons were promptly designed. With no time to build up a large stockpile on each side and therefore form the concept of mutually assured destruction, bombs were dropped the moment they were built. By the time they realized the long-term effects of such weapons, it was too late.

Now, the abandoned mecha litter the surface. While most of the technology found in the ruins is already known to us, the mecha provide an all new outlook of mechanics. Since so many can be found half-built, fully intact, and half-destroyed, we have plenty of opportunities to research them.”_

Options:
“Interesting.”

> Spawns a +2 Engineering deposit on the world, replacing any previous deposits. Also adds the “Mecha Graveyard” planetary modifier, which provides +10% Engineering research.

Failure:
**Unusual Ruins**
_“The unusual ruins on [Planet Name] are nothing more than just that: unusual ruins. It would appear as their now extinct builders had an interesting architectural style. Unfortunately, the buildings are far too deteriorated to be studied.”_

Options:
“Very well.”

> Nothing happens.

**Comment by Elimdur** [comment]
After reading through this event i got the feeling of sitting in a classroom hearing a teacher speaking about some historical events i never cared to know about.

Don´t get me wrong. The topic of this anomaly is interesting. But the way it is told sounds like these informations were common knowledge available in every library and not that they were gathered by scientists doing field work on an unknown world.

You should ask yourself if they would find all those infos you give in a matter of weeks on a long dead war torn world that has been destroyed in a nuclear war.

In my opinion you should give a plausible reason, why they can know so much or maybe make the infos more vague. 

Also it is hard to believe that a civilisation that not even had invented the atomic bomb would have been advanced enough in mechanics to build walking machines of war that would be comparable or even superior to wheeled or tracked tanks that we still use in our modern postatomic era while struggling to make any feasible walking machines at all. The closest you can find would be this https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiJp82z0Y7PAhVDOxQKHdFICpsQjRwIBw&url=http%3A%2F%2Fsciencev1.orf.at%2Fscience%2Fnews%2F58849&psig=AFQjCNHj7PlI_GkpAchbLc0r0S7vUJWagg&ust=1473934868418579 . And it should be said that because of its very slow movement compared to wheeled and tracked vehicles it would be of very low military use. To be of any use at all they would need to be capable of moving  on terrain  the other two kinds could not AND at a reasonable speed as well as being also atleast on the same level of usability on terrain these other vehicle can move on. Otherwise there would be no point in using them at all.

**Comment by tzerrell** [comment]
Seeing as one of the vanilla event pictures includes mecha (`ground_combat.dds`), I think they are considered part of the Stellaris universe. As for the rest ... I edited this a bit for pace but I left the length similar because I actually liked having a longer story. *shrug*

Anyway, I've implemented this and it's ready for testing, via `add_anomaly mem_abandoned_mecha_category`.

**Comment by Lukasmar** [comment]
Tested, works fine. Clear error log.

**Comment by tzerrell** [comment]
Closing this as testing is complete and I don't believe our translators use open issues to track their work as we have several languages.
